apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-cart-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopping-cart
  template:
    metadata:
      labels:
        app: shopping-cart
    spec:
      containers:
        - image: metatheory/shopping-cart:2022-12-29-23-12-33
          name: shopping-cart
          env:
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: jdbc:postgresql://snuffleupagus.db.elephantsql.com:5432/pkesgrkv
            - name: KUMULUZEE_DATASOURCES0_USERNAME
              value: pkesgrkv
            - name: KUMULUZEE_DATASOURCES0_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: shopping-cart-database-password
                  key: KUMULUZEE_DATASOURCES0_PASSWORD
            - name: RESTPROPERTIES_PRODUCTCATALOGBASEURL
              value: http://product-catalog:8080
            - name: RESTPROPERTIES_STORECATALOGBASEURL
              value: http://store-catalog:8080
          ports:
            - containerPort: 8080
              name: cart-port
              protocol: TCP
          imagePullPolicy: IfNotPresent

---

apiVersion: v1
kind: Service
metadata:
  name: shopping-cart
spec:
  type: NodePort
  ports:
    - port: 8080
      protocol: TCP
      targetPort: cart-port
  selector:
    app: shopping-cart