kumuluzee:

  name: shopping-cart-microservice

  env:
    name: dev

  version: 1.0.0

  server:
    base-url: http://localhost:8080
    http:
      port: 8080

  datasources:
    - jndi-name: jdbc/ShoppingCartsDS
      connection-url: jdbc:postgresql://localhost:5432/central
      username: dbuser
      password: postgres
      max-pool-size: 20

  # Database health check - check if datasource is available.
  # See https://github.com/kumuluz/kumuluzee-health#datasourcehealthcheck
  # for more information.
  health:
    checks:
      data-source-health-check:
        jndi-name: jdbc/ShoppingCartsDS
        type: liveness

rest-properties:
  product-catalog-base-url: "http://localhost:8080"
  store-catalog-base-url: "http://localhost:8081"