kumuluzee:

  name: shopping-cart-microservice

  env:
    name: dev

  version: 1.0.0

  server:
    base-url: http://localhost:8082
    http:
      port: 8082

  datasources:
    - jndi-name: jdbc/ShoppingCartsDS
      connection-url: jdbc:postgresql://localhost:5432/central
      username: dbuser
      password: postgres
      max-pool-size: 20

  rest-properties:
    product-catalog-base-url: "http://localhost:8080"

  cors-filter:
    annotations:
      my-resource:
        allow-origin: "*"
        allow-subdomains: true